const Data = [
    {
        id: 1,
        title: 'Sitting-Room',
        path: require('../../Assets/Categories/image (1).png'),
        product: [
            {
                id: 1,
                name: 'Modern-Fabrix-Accent-Chair',
                prize: 129,
                color1: '#878DBD',
                color2: '#EBD2B6',
                imagepath: require('../../Assets/Products/image (1).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (14).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (33).jpg'),
                delprize: 200,
                rating: '⭐⭐⭐⭐',
                discount: 40,
            },

            {
                id: 3,
                name: 'Aurla-Fabric-Accent-Chair',
                prize: 67,
                color1: '#8FA26A',
                color2: 'grey',
                imagepath: require('../../Assets/Products/image (5).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (5).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (30).jpg'),
                delprize: 110,
                rating: '⭐⭐⭐⭐',
                discount: 40,
            },
            {
                id: 4,
                name: 'Loveseat-Compact-2-Seater-Furniture',
                prize: 120,
                color1: '#878DBD',
                color2: '#EBD2B6',
                imagepath: require('../../Assets/Products/image (7).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (18).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (19).png'),
                delprize: 240,
                rating: '⭐⭐⭐⭐⭐',
                discount: 50,
            },
            {
                id: 5,
                name: 'Modern-Upholstered-Accent',
                prize: 45,
                color1: '#8FA26A',
                imagepath: require('../../Assets/Products/image (8).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (10).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (16).png'),
                delprize: 100,
                rating: '⭐⭐⭐⭐',
                discount: 40,
            },
            {
                id: 6,
                name: 'Roundhill-Fabric-Accent-Chair',
                prize: 78,
                color1: '#878DBD',
                color2: '#EBD2B6',
                imagepath: require('../../Assets/Products/image (10).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (23).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (3).png'),
                delprize: 170,
                rating: '⭐⭐⭐⭐',
                discount: 50,
            },
            {
                id: 7,
                name: 'Round-Terra-Marble-Center-Table',
                prize: 66,
                color1: '#B89C83',
                color2: '#BCADA8',
                imagepath: require('../../Assets/Products/image (11).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (2).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (25).png'),
                delprize: 130,
                rating: '⭐⭐⭐⭐⭐',
                discount: 40,
            },
            {
                id: 8,
                name: 'Metro-Luxe-Duo-Sofa',
                prize: 150,
                color1: 'brown',
                imagepath: require('../../Assets/Products/image (13).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (17).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (28).png'),
                delprize: 330,
                rating: '⭐⭐⭐⭐⭐',
                discount: 50,
            },
            {
                id: 9,
                name: 'Luxe-Modern-Armchair',
                prize: 20,
                color1: '#B89C83',
                color2: '#BCADA8',
                imagepath: require('../../Assets/Products/image (15).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (9).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (11).png'),
                delprize: 50,
                rating: '⭐⭐⭐⭐⭐',
                discount: 40,
            },
            {
                id: 10,
                name: 'Round-Fluted-Accent-Center-Table',
                prize: 60,
                color1: '#B89C83',
                color2: '#BCADA8',
                imagepath: require('../../Assets/Products/image (16).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (25).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (2).png'),
                delprize: 120,
                rating: '⭐⭐⭐⭐',
                discount: 50,
            },
            {
                id: 11,
                name: 'Round-Terra-Marble-Side-Table',
                prize: 90,
                color1: '#878DBD',
                color2: '#EBD2B6',
                imagepath: require('../../Assets/Products/image (17).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (15).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (8).png'),
                delprize: 210,
                rating: '⭐⭐⭐⭐⭐',
                discount: 40,
            },
            {
                id: 12,
                name: 'Luxe-Modern-Round-Ottoman',
                prize: 236,
                color1: 'grey',
                imagepath: require('../../Assets/Products/image (18).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (34).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (35).png'),
                delprize: 470,
                rating: '⭐⭐⭐⭐⭐',
                discount: 50,
            },
            {
                id: 13,
                name: 'Faux-Leather-Sofa-Couch',
                prize: 199,
                color1: '#B89C83',
                color2: '#BCADA8',
                imagepath: require('../../Assets/Products/image (19).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (28).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (29).webp'),
                delprize: 420,
                rating: '⭐⭐⭐⭐⭐',
                discount: 40,
            },
        ],
    },
    {
        id: 2,
        title: 'Accessories',
        path: require('../../Assets/Categories/image (3).png'),
        product: [
            {
                id: 1,
                name: 'Utopia-Plant-Pots',
                prize: 160,
                color1: '#8FA26A',
                imagepath: require('../../Assets/Products/image (9).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (14).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (33).jpg'),
                delprize: 230,
                rating: '⭐⭐⭐⭐',
                discount: 40,
            },
            {
                id: 2,
                name: 'Ceramic-Flower-Vase',
                prize: 44,
                color1: '#8FA26A',
                imagepath: require('../../Assets/Products/image (2).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (12).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (13).png'),
                delprize: 120,
                rating: '⭐⭐⭐⭐',
                discount: 50,
            },
            {
                id: 3,
                name: 'Boucle-Accent-Chair',
                prize: 80,
                color1: '#878DBD',
                color2: '#EBD2B6',
                imagepath: require('../../Assets/Products/image (20).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (18).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (19).png'),
                delprize: 210,
                rating: '⭐⭐⭐⭐⭐',
                discount: 40,
            },
        ],
    },
    {
        id: 3,
        title: 'Kitchen',
        path: require('../../Assets/Categories/image (2).png'),
        product: [
            {
                id: 1,
                name: 'Kitchen-Bar-Stool',
                prize: 35,
                color1: '#B9A79B',
                color2: 'black',
                imagepath: require('../../Assets/Products/image (14).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (21).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (6).png'),
                delprize: 80,
                rating: '⭐⭐⭐⭐',
                discount: 40,
            },
        ],
    },
    {
        id: 4,
        title: 'Bedroom',
        path: require('../../Assets/Categories/image (4).png'),
        product: [
            {
                id: 1,
                name: 'Wooden-Accent-Chair',
                prize: 50,
                color1: '#6D7D8D',
                imagepath: require('../../Assets/Products/image (3).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (7).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (4).png'),
                delprize: 110,
                rating: '⭐⭐⭐⭐',
                discount: 40,
            },
            {
                id: 2,
                name: 'Modern-Ceramic-Lamp',
                prize: 76,
                color1: '#D29542',
                color2: 'red',
                imagepath: require('../../Assets/Products/image (4).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (24).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (26).png'),
                delprize: 150,
                rating: '⭐⭐⭐⭐⭐',
                discount: 50,
            },
            {
                id: 3,
                name: 'Natural-Wood-Table',
                prize: 98,
                color1: '#D9BEA4',
                imagepath: require('../../Assets/Products/image (6).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (32).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (20).png'),
                delprize: 210,
                rating: '⭐⭐⭐⭐⭐',
                discount: 40,
            },
            {
                id: 4,
                name: 'Ceramic-Rustic-Vase-Matte',
                prize: 49,
                color1: '#BCADA8',
                imagepath: require('../../Assets/Products/image (12).png'),
                pdimg1: require('../../Assets/PDimgs/PDimg (1).png'),
                pdimg2: require('../../Assets/PDimgs/PDimg (27).png'),
                delprize: 110,
                rating: '⭐⭐⭐⭐',
                discount: 40,
            },
        ],
    },
];

const jsonString = JSON.stringify(Data);
console.log(jsonString); 


export default Data;
